# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-operations
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: Agent Policy
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-cloud-operations.git
    sourceType: git
  actuationTool:
    type: Terraform
    version: '>= 0.13'
  examples:
  - name: agent_policy_detailed_example
    location: examples/agent_policy_detailed_example
  - name: agent_policy_simple_example
    location: examples/agent_policy_simple_example
  - name: agent_policy_update_example
    location: examples/agent_policy_update_example
  variables:
  - name: agent_rules
    description: A list of agent rules to be enforced by the policy.
    type: list(any)
    required: true
  - name: description
    description: The description of the policy.
    type: string
    required: false
  - name: group_labels
    description: A list of label maps to filter instances to apply policies on.
    type: list(map(string))
    required: false
  - name: instances
    description: A list of instances to filter instances to apply the policy.
    type: list(string)
    required: false
  - name: os_types
    description: A list of OS types to filter instances to apply the policy.
    type: list(any)
    required: true
  - name: policy_id
    description: The ID of the policy.
    type: string
    required: true
  - name: project_id
    description: The ID of the project in which to provision resources.
    type: string
    required: true
  - name: zones
    description: A list of zones to filter instances to apply the policy.
    type: list(string)
    required: false
  roles:
  - level: Project
    roles:
    - roles/owner
    - roles/osconfig.guestPolicyAdmin
    - roles/monitoring.metricWriter
    - roles/logging.logWriter
  services:
  - cloudresourcemanager.googleapis.com
  - serviceusage.googleapis.com
  - logging.googleapis.com
  - monitoring.googleapis.com
  - osconfig.googleapis.com
